language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - python manage.py test mainapp
  - coverage run --source=mainapp manage.py test mainapp
env:
  - COVERALLS_REPO_TOKEN=qiz2yB41KjYBxJacVhU4WIbeIIkFUMj6G
 
after_success:
  - coveralls
